### ISSUE TITLE
[TEC Tile] Power Generation Variant

### ISSUE THREAD

**Issue by smellymoo** [romen-h/ONI-Mods#17]
Hi there,

I am a C++ programmer that has a very popular game ([sand:box](https://play.google.com/store/apps/details?id=smellymoo.sand), 50 million downloads) and have always been a major fan on ONI, but since first playing it I have been waiting for a TEC to be added, but haven't had the time to make the mod myself... So thank you for that!

The design I was originally looking to make would have been reversible (power <=> heat differential) and have waste heat added on the hot side / inefficiency in power generation like a real TEC.

Do you mind if I fork your build and release a mod with these changes? or maybe we could work on it together?

also is it possible to have a building switch between power consumer to generator?

**Comment by romen-h** [comment]
Hi!

## Regarding Licensing & Forking

I have not decided on licensing for my code or artwork yet so I really appreciate the fact that you asked.
My only concerns are around preventing modified works that are too similar or low effort from appearing on the Steam Workshop, so that is why I hesitated on picking the license for this repo.

I am completely happy to work with you on making this mod better and I am open to PRs. Go ahead and make the fork so you can at least contribute back to this repo. I will ponder the license some more and maybe look at granting a license to just you to fork & upload a modified version to Workshop.

## Regarding your ideas:

### Inefficiency
This is already in the mod. There is an options menu in the mods list that lets you toggle a "Generate Waste Heat" setting. This setting should be enabled by default too.
It will cause a significant amount of heat to be generated in the building as it is powered and it is proportional to some other settings for the building too.  
[TECTileConfig.cs : Line 43](https://github.com/romen-h/ONI-Mods/blob/37092148178061dbce7434424f7e49c2ed3e676b/src/TECBlock/TECTileConfig.cs#L43)

### Reversible
This wasn't something that I considered for this mod at all, and you can see the artwork leans into a very one-way looking design. It has heat sink fins on the hot side and a plate on the cold side, and each side has a slight colourization representing whether it's hot or cold. So with all of that, I'd say a reversible TEC would need totally new art.  
Another thought I had about why it wasn't reversible would be that ONI's circuitry isn't reversible and automation is already used to control whether the TEC is on or off. There doesn't actually seem like there's any method left to reverse the TEC anyway.

### Power Generation
Making a building consume power and generate power in ONI is extremely complex and I drew the line at making this TEC specifically for consuming power in order to move heat.
I have another mod called Stirling Engine too that already consumes heat to produce power, so I felt that was too similar to a TEC "generator".

**Comment by smellymoo** [comment]
Excellent! I am just wrestling with getting my IDE to build (as I'm on Linux and don't use C#). Once that happens I can start exploring the options.

Reversing which side is hot isn't worth the effort, you are right. I wasn't thinking of that actually, I just mean to use it both ways (generator / cooler). With this idea the hot side would always be the same, meaning you could heat something and then draw power treating the heated area (and cooled) like a thermal battery (just super inefficient). 

About the waste heat, in a real TEC it is added to the hot side.

I have a few ideas of how it might be possible to make it work both ways, are any viable:
- make it work like a small battery.
- add 2 plugs, making the plate 2 tiles.
- making the plug switch between in / out based on the heat diff, if under a threshold it's cooling, over it's a generator.
- building has a toggle. Maybe that swaps itself out for the other form invisibly.
- have 2 variants :(. 

Does your Stirling engine use a heat differential like a real one? If so I'll look at it too.

Thanks for your reply, excited about trying out what we can do. A full TEC would be such a brilliant addition to ONI.

**Comment by romen-h** [comment]
I think making a 2nd building for generating heat - A "Thermoelectric Generator" or "TEG" would be the simplest way to do this.

I am perfectly happy adding that to my mod and making the art for it too.
I would like to make sure it doesn't work too similarly to Stirling Engine so that both mods remain useful for different use cases; Would you be able to advise on some of the math and physics behind running actual TECs as a generator?

I understood that they have a maximum heat difference that they can sustain before they hit some equilibrium. (Usually up to 70 C?)
When they're used to generate a current does that mean a temperature difference over ~70C will generate no extra power?

**Comment by smellymoo** [comment]
Sure, I'll have a look. But from memory, it will probably be very similar to the Stirling engine. The temperature difference needs to be over a certain amount before it generates anything, and it has a maximum amount too.

It's really a shame there doesn't seem to be a way oni can handle it doing both in one. The battery idea would have lots of issues.

**Comment by smellymoo** [comment]
> Would you be able to advise on some of the math and physics behind running actual TECs as a generator?

From a quick look it seems that it doesn't produce power until the difference is higher than 10-15 degrees.... Then it's fairly linear.

2 things are the maximum hot side temp, which I guess would damage the building, around 150 degrees. And max temp difference, which I think would stop producing more power.

Maybe for game balance it would be too easy if you could use it on steam? So the max could be 90?

**Comment by romen-h** [comment]
> From a quick look it seems that it doesn't produce power until the difference is higher than 10-15 degrees.... Then it's fairly linear.

The Stirling Engine also has this kind of minimum difference just to ensure it's not contributing extremely small wattage values into the power grid. There's no physical reason the engine can't generate extremely small amounts of power off any heat small gradient.

The linear response to heat differential is actually something that makes it stand out from Stirling Engine so we should double down on it if we're making this building at all.

The Stirling Engine uses the ratio `1 - (Cold / Hot)` to determine efficiency, so it means that really extreme temperatures are needed to generate decent amounts of power. That makes it ideal for using in very cold rooms, or on top of very hot rooms.

If a TEC just cares about the delta `Hot - Cold` at any temperature, then it's useful for generating more power than the Stirling Engine in room temperature environments.

A room-temperature 293K "cold" side and a 373K "hot" side would mean Stirling Engine is only ~21% efficient, but that's an 80K delta that would probably max out the power generated by the TEG.

**Comment by romen-h** [comment]
It looks like a TEC used to generate power is called a "Seebeck Module".
Some quick searching online suggest that various models do also have a minimum temperature for them to operate at.

I think I recall something about TECs being more efficient at higher temperatures and when they get too cool they just don't move heat. So for a TEG there would probably be some linear efficiency scaling from the minimum temperature (no damage) to the max temperature (takes damage)?

**Comment by smellymoo** [comment]
https://www.quora.com/Is-a-Peltier-chip-or-Sterling-Engine-more-efficient

Seems that TEG is less than half as effecient than a peltier, but much more linear power curve, so it's best as it's pretty unbreakable and low maintenance also compact...

So I guess to differentiate them, if Stirling is bigger and only works efficiently in a small temperature range and breaks at a temp max... Whereas the TEG works for a larger range before breaking, but tops out at say 70 degrees delta, and is really inefficient, and is 1 tile... That would then have very different use cases, TEG would be just for small amounts of power in remote places.

**Comment by romen-h** [comment]
> So I guess to differentiate them, if Stirling is bigger and only works efficiently in a small temperature range and breaks at a temp max... Whereas the TEG works for a larger range before breaking

Stirling Engine already released and I don't want to change the way it works.  
The Stirling Engine **does not** work efficiently in a small temperature range right now, and it **does not** break easily. The math for a theoretical heat engine scales up power generation **non-linearly** with heat gradient. So more extreme gradients will lead to more efficient engine operation and this building is **only** useful for generating power off of extreme temperature gradients.

**Comment by smellymoo** [comment]
Interesting. I guess if it has very low efficiency and breaks, it will still be useful, for example on a steam vent or near a frozen biome to make a small amount of power for a pump.

Small, simple, not too useful to break gameplay or to compete with the Stirling engine.

**Comment by smellymoo** [comment]
Do you think maybe I should make the TEG, and make it generally make sense with your 2 mods? Or are you wanting to take it up?

**Comment by romen-h** [comment]
You're free to make your own TEG mod. 
Please do not reuse my art. Feel free to use the Stirling Engine code as learning material since that one is much more useful than the TEC mod for generating power from heat.

I do also intend to update this mod with my own TEG like what I described above; I'm just too busy to work on mods this week.

**Comment by romen-h** [comment]
I have started working on a TEG building. Still playing around with balance and some temperature movement bugs.

A question for you @smellymoo 

Should the TEG only absorb heat from the "hot" side? Should it not move any heat through it because all of the heat that does get moved becomes electricity?

**Comment by smellymoo** [comment]
First of all, thank you so much for your great work and hearing suggestions, I'm excited to see your TEG when finished :D.

So I would think about it as it being symmetrical, simular to pumped hydro, the motor can work to pump the water, and the higher the difference the more energy used to pump the water, and then when reversed the pressure of the flow makes more as it flows back, and eventually stops when the water is at the almost the same level. Although it's worth thinking about the voltage and current seperately in that example, in ONI it's Watts...

So I guess you could actually just give the TEG block a thermal conductivity that will let the temperature across it equalise, and then use the temp difference to decide how much power it makes. That might be the simple way to do it. It might not be perfectly accurate, and would mean you could put it the wrong way around or mean you could use it say in diagonal heat transfer...

So if that doesn't work or you want it to be perfect, maybe use the simple heat transfer (by conductivity) equation between the 2 tiles, and then change their temp to equalise them slowly, and generate power from the temp flow flux, I can find that equation for you, used it recently.

**Comment by smellymoo** [comment]
flux = (heatA - heatB) / restivity;

heatA -= flux / massA;
heatB += flux / massB;

**Comment by romen-h** [comment]
Those formulas look really useful.
It looks like the math for moving energy from one side to the other when provided a current though? (Peltier effect)

I was mainly wondering about the reverse, when you have a temperature difference it generates a current and the temperature difference becomes equalized as that energy is sapped away into the circuit.
- Does the cold side get hotter as the hot side gets colder?
- Does the energy come entirely from the hot side until it's equalized to the cold side?

**Comment by smellymoo** [comment]
if you think about it, TEC / TEG are the same but reversed, the only oddity is the inefficiency, so that equation can be used for both.

the heat flux is proportional to the watts of power produced in the TEG, with a percentage taken off for inefficiency. And the other way, the amount of heat moved in a TEC is proportional to the watts of power put in, with a percentage lost, but that you then add as heat anyway.

yes, the cold side gets hotter, and the hot side gets cooler.... best way to think about it is just as a heat conductive tile... but a relatively small percentage of the heat travelling through converts to watts.

The energy comes from the heat flux, which is the movement of heat, in physics there is only heat, cold is the absence of heat, so technically the heat flows from the hot side to the cold... but as the TEG generates power from the temperature flux, you can imagine it both ways round, as long as you know in reality there is only heat. if you only cooled down the cold side, it would make power, but that power would be from the room temperature flowing through to the colder side.

simple way of making the TEG work and understand it is it's just a heat conductive tile, and a percentage is taken as power... so decide a realistic thermal reactivity for the tile, then do 2 steps of equalising the temperatures, first between the hot side, and TEG, then the TEG and the cold side. I guess you add the 2 fluxes together for the total flow?


fluxHOT = (tempHOT - tempTEG) / (restivityHOT + restivityTEG);
fluxCOLD = (tempCOLD - tempTEG) / (restivityCOLD + restivityTEG);

fluxTOTAL = fluxHOT + fluxCOLD;

then you know how much heat is flowing, take a percentage as electrical power, then change the hot side and cold side:

tempHOT -= fluxHOT / massHOT;
tempCOLD += fluxCOLD / massCOLD;

tempTEG += (fluxHOT - fluxCOLD) / massTEG;

something like that :)

**Comment by romen-h** [comment]
Uploaded 3.0.0 today with a TEG tile building.
