### ISSUE TITLE
[Stirling Engine] Efficiency/heat dumping adjustment 

### ISSUE THREAD

**Issue by stords** [romen-h/ONI-Mods#25]
Hey, love the idea for this mod. I had a suggestion that I think might help balance while being consistent with thermodynamics

My understanding from your code (maybe I am misreading) is that the heat generated on the engine is the `wasteHeatRatio` and not the leftover heat (1 - efficiency), although it looks like you did try that out at some point. I'm assuming you made this choice because using leftover heat would be balance-breaking when operating near 0K max efficiency.

This has a problem, however, that makes the engine kind of an OP heat destruction tool when the difference in temperature is low. For example, running an engine between 40C and 20C has an efficiency of ~7%, so it barely makes electricity. However, since it only passes `wasteHeatRatio` through (default 10%) the engine is basically just sucking up heat and destroying it completely for free. Obviously, you can just avoid using them in this way if you think its OP, but I think a simple change would fix this and have other positive effects too. 

A solution would be to calculate "wasted heat" and subtract it from the heat going to power, and then use the "leftover heat" to determine the heat transfer to the engine. The efficiency becomes (1 - Tc / Th) * (1 - wasteHeatRatio) where Tc is the cold temp, Th is the hot temp. This works thermodynamically because it's just saying that some fraction of the work done is converted to heat on the cold side due to non-ideal conditions (e.g. friction).

Not only does this fix the OP heat destruction, it also has a balance benefit in lowering the maximum efficiency possible, making it less game-breaking to run an engine near 0K. Personally, I think this solution would strike a pretty good balance.

**Comment by romen-h** [comment]
> I'm assuming you made this choice because using leftover heat would be balance-breaking when operating near 0K max efficiency.

It seems to me that your `(1 - Tc / Th) * (1 - wasteHeatRatio)` suggestion is the same thing as the disabled code in the PRODUCE_LEFTOVER_HEAT section. In that case the only heat that is deleted is exactly the heat that becomes power, and the rest goes into the building. While that was very realistic, it didn't feel fun or useful in early game and that's why I decided to go with the completely unrealistic `wasteHeatRatio`. It ended up making a lot more users happy and eliminating some complaints that seemed to be coming from the game design being at odds with trying to base things on real physics.


I did want to do the math and show you that the machine isn't deleting heat for free, you (*should be*) getting a fair amount of power for the heat that gets deleted with this made-up physics. (So it becomes useful and fun)

> For example, running an engine between 40C and 20C has an efficiency of ~7%, so it barely makes electricity. However, since it only passes wasteHeatRatio through (default 10%) the engine is basically just sucking up heat and destroying it completely for free. 

Let's do all of the math on that scenario.

```
T_Hot = 313.15 K (40C)
T_Cold = 293.15 K (20C)
Efficiency = 1 - (T_Cold / T_Hot) = ~0.0639 = 6.39%
MaxHeatToPump = 100W * 100 DTU/W = 10000 DTU
ActualHeatToPump = MaxHeatToPump * Efficiency = ~638 DTU
WorkHeat = ActualHeatToPump * Efficiency // Oops! Found a bug applying efficiency twice!
```
Tracking two numbers with & without bug from here.
```
WattsGenerated = WorkHeat / 100 DTU/W = 0.4W (Actual),  6.38W (Bug Fixed)
WasteHeat = WorkHeat * 0.1 = 0.04 DTU (Actual),  63.8 DTU (Bug Fixed)
DeletedHeat = WorkHeat - WasteHeat = ~637.96 DTU (Actual), 574.2 DTU (Bug Fixed)
```
Right now it generates 0.4W and deletes ~638W to make that.
Giving 1595 DUT/Watt conversion!! That's 15x higher than I intended.

Without applying efficiency twice, it would generate 6.38W and deletes ~574 DTU to make that.
Giving 90 DTU/Watt conversion after all of that.

Deleting 90 DTUs to make 1 Watt isn't in the territory of "Deleting heat for free", that seems like a completely reasonable amount of heat to delete for the wattage you are getting. Once I fix that bug it makes the engine generate a lot more power too, and will become more useful in low temperature gradients. How do you think that would affect the 0K situations?
