### ISSUE TITLE
GermicideLamp: Germicide Lamp don't kill all germ on pickupable objects.

### ISSUE THREAD

**Issue by jacob-thanh** [romen-h/ONI-Mods#4]
It's just a small bug, I guess. However, with different germicidal strength, sometimes when I use it to cleanse slime, there will always be one stubborn germ left that won't die. I guess it has something do to with floating point calculation in the [Mathf.clamp](https://github.com/romen-h/ONI-Mods/blob/957c101d787a9e81edbc5808a32475ba63208b4e/src/GermicideLamp/GermicideLamp.cs#L29) that is round down to 0 sometimes, so it won't be killed at all.
PS. Your github commit is quite old, the last mod update is 28 Jun @ 9:42pm. Your commit was from like 5 months ago. 
The current GermicideLamp code got some error. I need to edit some file to got it build.
----The [namespace](https://github.com/romen-h/ONI-Mods/blob/957c101d787a9e81edbc5808a32475ba63208b4e/src/GermicideLamp/Patch.cs#L2) is inconsistent (should be [RomenH.Common](https://github.com/romen-h/ONI-Mods/blob/957c101d787a9e81edbc5808a32475ba63208b4e/src/CommonLib/CommonLib.csproj#L10))
----The [function name from Patch.cs](https://github.com/romen-h/ONI-Mods/blob/957c101d787a9e81edbc5808a32475ba63208b4e/src/GermicideLamp/Patch.cs#L28-L29) is inconsistent, the params are also in [reversed order](https://github.com/romen-h/ONI-Mods/blob/957c101d787a9e81edbc5808a32475ba63208b4e/src/CommonLib/Utils.cs#L39)
----These [two params](https://github.com/romen-h/ONI-Mods/blob/957c101d787a9e81edbc5808a32475ba63208b4e/src/GermicideLamp/Patch.cs#L17-L18) also in [reversed order](https://github.com/romen-h/ONI-Mods/blob/957c101d787a9e81edbc5808a32475ba63208b4e/src/CommonLib/Utils.cs#L21)
Would you update your code please? 
Thank you for your mods.

**Comment by romen-h** [comment]
Thanks for the feedback.
It makes sense that it would fail to kill the last single germ because of the float to int cast. I will quickly update the mod so everyone can enjoy that fix.

Pushing code to Github right now would be premature and just bring more messes, but I will try to make sure that the repo is always buildable for now on. The edits you had to make were due to a partial commit and I will try to avoid doing that. I will update the repo for all of my mods at once when they're updated for mergedown and the "messes" are cleaned up.

**Comment by romen-h** [comment]
This should be fixed in the latest builds on steam, and changes for this were pushed to github a while ago.
