### ISSUE TITLE
The stirling engine and a problem with balance;

### ISSUE THREAD

**Issue by Vectrobe** [romen-h/ONI-Mods#8]
The problem with the balance is with the formula, combined with ONI's law-breaking Thermo-X machines; when you cool the stirling engine closer and closer to 0K, say by using a H2 loop with a regulator (21K-ish minimum), the formula stops working as you would expect and the engine just saps heat and generates power by rather ridiculous amounts.
So at 21K for example, you only need the hot side to be 42K and its already at half power, 84K at 75% power, and so on. Essentially a row of these with a single regulator makes for a rather overpowered sour gas > methane converter.

I suggest changing the formula to be more difference-relative as opposed to relative to 0K, and also dropping the power production to say 50W with much more heat output? real-life heat engines (turbines, pistons, stirling's, etc) can usually only obtain 50% conversion at most so the closer these are to that the more 'balanced' they'll appear.

Since the mod is using C#, and I assume unity's built-in features are accessible? You can use an animation curve to fine-tune it, with a formula like so;

```cs

UnityEngine.AnimationCurve powerCurve = new UnityEngine.AnimationCurve(new Keyframe[]
    { new Keyframe(0f, 0f), new Keyframe(100f, .25f) , new Keyframe(200f, 1f) } );

float relativeValue = hotSide - coldSide;
// note that the values will be clamped to the min and max given in the curve
float result = powerCurve.Evaluate(relativeValue);
float powerProduction = result * 50;
float heatInput = result * 10000;
float heatOutput = result * 2500;

```

This would still not be 'realistic' persay, but not much of ONI' actually is anyway, but in the end I feel this would make for an optimal balance. You can of course tune that animation curve however you want, and add a if(result < .1f) check for example so it only works above a certain range, or just add that to the curve as well, up to you.

(oh and animation curves can be edited in the unity editor if they are a public variable on a game object, if ONI's modding uses prefabs then that would be a simple way to tune it)

**Comment by romen-h** [comment]
I am not planning to change this mod in any significant way, I made it configurable so that everyone who felt it was unbalanced could re-balance it themselves. But the underlying math is "correct" in my opinion, it is modelled after real physics.

I did a lot of research and modelled the equations for this mod after real physics. The problem is ONI isn't very realistic and it enables you to put a **real** stirling engine in unrealistic environments.

> So at 21K for example, you only need the hot side to be 42K and its already at half power ...
> I suggest changing the formula to be more difference-relative as opposed to relative to 0K

The math isn't relative to 0K, your example of `21K / 42K` is just as efficient as `200 K / 400 K`, or `8000 K / 16000 K`. The efficiency is proportional to the ratio between the temperatures. This is real physics.  
When you are at values so close to 0K, it is easier to achieve those extreme ratios, because adding a few degrees to either side can change the ratio significantly. *However*, this is still realistic. If you brought a real stirling engine into a lab and cooled it down that much it would be wildly efficient!
